# Generated by Django 3.1.3 on 2020-12-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_ShiPin_Report',
            fields=[
                ('ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Dropdown_BiSaiJieGuo', models.CharField(max_length=32)),
                ('Date_field_BiSaiRiQi', models.CharField(max_length=32)),
                ('Url', models.TextField(max_length=1000)),
                ('Query_SaiShiMingCheng_ID', models.CharField(max_length=100)),
                ('form_YunDongYuan_B1_ID', models.CharField(max_length=128)),
                ('form_YunDongYuan_B2_ID', models.CharField(max_length=32)),
                ('Single_Line_ShiPinMingCheng', models.CharField(max_length=255)),
                ('Query_SaiShiMingCheng', models.CharField(max_length=100)),
                ('Formula_InputTimDate', models.CharField(max_length=100)),
                ('Dropdown_BiSaiXiangMu', models.CharField(max_length=32)),
                ('Dropdown_LunCi', models.CharField(max_length=32)),
                ('form_YunDongYuan_ShengLi_2', models.CharField(max_length=32)),
                ('Dropdown_QueShi', models.CharField(max_length=32)),
                ('form_YunDongYuan_A2', models.CharField(max_length=32)),
                ('form_YunDongYuan_ShengLi_1', models.CharField(max_length=32)),
                ('form_YunDongYuan_A1', models.CharField(max_length=32)),
                ('form_YunDongYuan_B2', models.CharField(max_length=32)),
                ('form_YunDongYuan_B1', models.CharField(max_length=32)),
                ('form_YunDongYuan_A1_ID', models.CharField(max_length=32)),
                ('form_YunDongYuan_A2_ID', models.CharField(max_length=32)),
                ('Single_Line_BiFen', models.CharField(max_length=32)),
                ('Added_Time', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'form_ShiPin_Report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='video_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'video_user',
                'managed': True,
            },
        ),
    ]
